/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet-earth-hi-res.glb --transform 
Files: planet-earth-hi-res.glb [15.26MB] > /home/sam/projects/animations-demo/public/models/planet-earth-hi-res-transformed.glb [344.42KB] (98%)
Author: murilo.kleine (https://sketchfab.com/murilo.kleine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-terra-downloadable-model-30fd7e9c4e6946ddb6fcae7a97b2b0d4
Title: Earth | Terra - Downloadable model
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/planet-earth-hi-res-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.Armature_rootJoint} />
        <mesh name="EARTH_0" geometry={nodes.EARTH_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="ATM_0" geometry={nodes.ATM_0.geometry} material={materials['Material.002']} skeleton={nodes.ATM_0.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/planet-earth-hi-res-transformed.glb')
